#!/bin/bash

#the task: create a globbing pattern to math the given descriptor! 

#All non-hidden files in the current directory with atleast 2 character prefix and ending in .h, .C, .cc, .cpp
echo ??*.{h,C,cc,cpp}

#All non-hidden files in the current directory that start and end with a letter.
echo [a-zA-Z]*[a-zA-Z] [a-zA-Z]

#All files in the directories A1,A2,A3,A4 starting with cs.
echo A[1-4]/cs*
